[agents]
amp = false
claude-code = true
codex = true
factory = false
opencode = false

[dependencies]
ground = { gh = "pentaxis93/groundwork", path = "skills/ground" }
research = { gh = "pentaxis93/groundwork", path = "skills/research" }
bdd = { gh = "pentaxis93/groundwork", path = "skills/bdd" }
begin = { gh = "pentaxis93/groundwork", path = "skills/begin" }
plan = { gh = "pentaxis93/groundwork", path = "skills/plan" }
issue_craft = { gh = "pentaxis93/groundwork", path = "skills/issue-craft" }
land = { gh = "pentaxis93/groundwork", path = "skills/land" }
propose = { gh = "pentaxis93/groundwork", path = "skills/propose" }
documentation = { gh = "pentaxis93/groundwork", path = "skills/documentation" }
using_groundwork = { gh = "pentaxis93/groundwork", path = "skills/using-groundwork" }
third_force = { gh = "pentaxis93/groundwork", path = "skills/third-force" }
subagent_driven_development = { gh = "obra/superpowers", path = "skills/subagent-driven-development", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
test_driven_development = { gh = "obra/superpowers", path = "skills/test-driven-development", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
systematic_debugging = { gh = "obra/superpowers", path = "skills/systematic-debugging", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
verification_before_completion = { gh = "obra/superpowers", path = "skills/verification-before-completion", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
requesting_code_review = { gh = "obra/superpowers", path = "skills/requesting-code-review", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
receiving_code_review = { gh = "obra/superpowers", path = "skills/receiving-code-review", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
