[agents]
amp = false
claude-code = true
codex = false
factory = false
opencode = false

[dependencies]
foundation = { path = "./skills/foundation" }
specification = { path = "./skills/specification" }
decomposition = { path = "./skills/decomposition" }
completion = { path = "./skills/completion" }
using-groundwork = { path = "./skills/using-groundwork" }
ground = { gh = "pentaxis93/groundwork", path = "skills/foundation/ground" }
research = { gh = "pentaxis93/groundwork", path = "skills/foundation/research" }
bdd = { gh = "pentaxis93/groundwork", path = "skills/specification/bdd" }
planning = { gh = "pentaxis93/groundwork", path = "skills/decomposition/planning" }
issue_craft = { gh = "pentaxis93/groundwork", path = "skills/decomposition/issue-craft" }
land = { gh = "pentaxis93/groundwork", path = "skills/completion/land" }
using_groundwork = { gh = "pentaxis93/groundwork", path = "skills/using-groundwork" }
brainstorming = { gh = "obra/superpowers", path = "skills/brainstorming", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
writing_skills = { gh = "obra/superpowers", path = "skills/writing-skills", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
writing_plans = { gh = "obra/superpowers", path = "skills/writing-plans", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
subagent_driven_development = { gh = "obra/superpowers", path = "skills/subagent-driven-development", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
test_driven_development = { gh = "obra/superpowers", path = "skills/test-driven-development", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
systematic_debugging = { gh = "obra/superpowers", path = "skills/systematic-debugging", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
verification_before_completion = { gh = "obra/superpowers", path = "skills/verification-before-completion", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
requesting_code_review = { gh = "obra/superpowers", path = "skills/requesting-code-review", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
receiving_code_review = { gh = "obra/superpowers", path = "skills/receiving-code-review", rev = "e4a2375cb705ca5800f0833528ce36a3faf9017a" }
